# Generated by Django 4.0.2 on 2022-03-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Accounts',
        ),
    ]
