# Generated by Django 4.0.2 on 2022-03-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_rename_users_accounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
    ]
