# Generated by Django 4.0.2 on 2022-03-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_rename_accounts_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
